#include <ice/ice.idl>

module ice {
  struct GlobalSimulationObjective {
    @key MetricIdentifier metric_id;
    float value;
    @doc("0 if no jitter")
    float jitterStep;
    @doc("'hard stop' limit of the model")
    float floor;
    @doc("'hard stop' limit of the model")
    float ceil;
  };
  const string GlobalSimulationObjectiveTopic = "GlobalSimulationObjective";

  struct LocalSimulationObjective {
    @key UniqueDeviceIdentifier unique_device_identifier;
    @key MetricIdentifier metric_id;
    float value;
  };
  const string LocalSimulationObjectiveTopic = "LocalSimulationObjective";
};
